### PR TITLE
added transaction and advisory lock

### PR DESCRIPTION
**Pull request by JaredBoone**
Fixes https://github.com/numtel/pg-live-select/issues/12

### CODE REVIEW

**Comment by numtel** [comment]
Can you make a test case that fails without this patch? You are seeing this error when starting 2 instances simultaneously? Is it using a unique channel for each instance?

**Comment by JaredBoone** [comment]
I am seeing this error when using child_process fork() to run 2 instances simultaneously. The instances in my application are currently using the same channel. I have just now tried using uniquely named channels and that seems to work. 

I have some "demonstration" code, but it's not in unit test form yet.

parent.js:
```
const { fork } = require('child_process');

const child1 = fork('child.js');
child1.send('start');
child1.on('message', result => {
    console.log('Child 1: ' + result);
});

const child2 = fork('child.js');
child2.send('start');
child2.on('message', result => {
    console.log('Child 2: ' + result);
});
```

child.js:
```var fs = require('fs');
var path = require('path');
var LivePg = require('pg-live-select');

var CONN_STR = 'postgres://meteor:meteor@127.0.0.1/meteor';
var QUERY = fs.readFileSync(path.join(__dirname, 'livequery.sql')).toString();

const start = () => {
  var liveDb = new LivePg(CONN_STR, 'mytest');
  liveDb.select(QUERY, [ 1 ])
    .on('update', function(diff, data) {
      process.send(diff);
    });
}

process.on('exit', function() {
  if (liveDb) {
    liveDb.cleanup(function(){
      console.log('liveDb cleaned up after exit');
      });
    }
  }
);

process.on('message', (msg) => {
  start();
});
```

**Comment by numtel** [comment]
This package is designed so that the channel must be unique. Sorry if that wasn't clear enough in the readme.

Implementing a change like this would be more complicated than just this change. If instances shared the channel, the `cleanup` function would stop any more updates coming on all listeners to that channel. Although there may be a small performance improvement from sending fewer notifications from Postgres, I'm not convinced that this change is necessary.

**Comment by JaredBoone** [comment]
OK, thanks, I'll use unique channels instead.

**Pull request closed without merging**
